<a href="https://colab.research.google.com/github/ChandraseharR/ailab/blob/main/HITS%2CPagerank%2CRecommendation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


HITS AND PAGERANK



In [1]:
outlinks = [
    ('E', 'F', 0.25),
    ('E', 'C', 0.35),
    ('E', 'D', 0.7),
    ('E', 'B', 0.6),
    ('B', 'E', 0.5),
    ('B', 'C', 0.32),
    ('F', 'C', 0.79),
    ('F', 'H', 0.85),
    ('G', 'A', 0.2),
    ('G', 'C', 0.12),
    ('C', 'A', 0.37),
    ('H', 'A', 0.64),
    ('A', 'D', 0.29),
    ('D', 'B', 0.85),
    ('D', 'C', 0.2)]

In [2]:
def find_no_of_pages(outlinks):
  lst=[]
  for row in outlinks:
    lst.append(row[0])
  lst=sorted(list(set(lst)))
  return lst

In [3]:
def create_adj(pages,outlinks):
  n=len(pages)
  adj=[[0 for i in range(n)] for i in range(n)]
  for row in outlinks:
    adj[pages.index(row[0])][pages.index(row[1])]=1
  return adj

In [4]:
import numpy as np
def create_hyperlink(adj):
  row_sum=np.sum(adj,axis=1,keepdims=True)
  hyperlink=adj/row_sum
  return hyperlink

In [5]:
def create_g_mat(alpha,h_mat):
  n=len(h_mat)
  for i in range(n):
    row=h_mat[i]
    row_sum=sum(h_mat[i])
    if row_sum==0:
      h_mat[i]=[1/n]*n
  return alpha*h_mat+(1-alpha)/n

In [6]:
def page_rank(g_mat):
  n=len(g_mat)
  prev_pr=np.zeros(n)
  prev_pr[0]=1
  ct=0

  while ct<100:
    ct+=1
    cur_pr=np.dot(prev_pr,g_mat)
    if np.linalg.norm(cur_pr - prev_pr)<1e-8:
      print(ct)
      return cur_pr
    prev_pr=cur_pr

In [7]:
def calc_hits(adj):
  n=len(adj)
  prev_hub=np.ones(n)
  prev_auth=np.ones(n)
  ct=0

  while ct<100:
    ct+=1

    new_hub=np.dot(adj,prev_auth)
    new_hub/=sum(new_hub)

    new_auth=np.dot(adj.T,prev_hub)
    new_auth/=sum(new_auth)

    if np.linalg.norm(new_hub-prev_hub)<1e-8 and np.linalg.norm(new_auth-prev_auth)<1e-8:
      print(ct)
      return new_hub,new_auth
    prev_hub,prev_auth=new_hub,new_auth

In [15]:
def principal_eigen(A):
  eig_val,eig_vec=np.linalg.eig(A)
  principal_eig_index=np.argmax(eig_val)
  ev=eig_vec[:,principal_eig_index]
  return np.divide(ev,sum(ev))

In [9]:
pages=find_no_of_pages(outlinks)
pages

['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H']

In [11]:
adj=create_adj(pages,outlinks)
adj

[[0, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 1, 0, 1, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 1, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 0, 1, 0, 0],
 [0, 0, 1, 0, 0, 0, 0, 1],
 [1, 0, 1, 0, 0, 0, 0, 0],
 [1, 0, 0, 0, 0, 0, 0, 0]]

In [12]:
h_mat=create_hyperlink(adj)
h_mat

array([[0.  , 0.  , 0.  , 1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 0.5 , 0.  , 0.5 , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 0.25, 0.25, 0.25, 0.  , 0.25, 0.  , 0.  ],
       [0.  , 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.5 ],
       [0.5 , 0.  , 0.5 , 0.  , 0.  , 0.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  , 0.  ]])

In [13]:
g_mat=create_g_mat(0.9,h_mat)
g_mat

array([[0.0125, 0.0125, 0.0125, 0.9125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.0125, 0.0125, 0.4625, 0.0125, 0.4625, 0.0125, 0.0125, 0.0125],
       [0.9125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.0125, 0.4625, 0.4625, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.0125, 0.2375, 0.2375, 0.2375, 0.0125, 0.2375, 0.0125, 0.0125],
       [0.0125, 0.0125, 0.4625, 0.0125, 0.0125, 0.0125, 0.0125, 0.4625],
       [0.4625, 0.0125, 0.4625, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125],
       [0.9125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125, 0.0125]])

In [17]:
pr1=page_rank(g_mat)
pr2=principal_eigen(g_mat.T)
k=3
top_pages=np.argsort(pr2)[::-1][:k]
pr1,pr2,top_pages

60


(array([0.24278768, 0.14127274, 0.22379784, 0.24812528, 0.07607273,
        0.02961637, 0.0125    , 0.02582736]),
 array([0.24278768+0.j, 0.14127274+0.j, 0.22379784+0.j, 0.24812528+0.j,
        0.07607273+0.j, 0.02961636+0.j, 0.0125    +0.j, 0.02582736+0.j]),
 array([3, 0, 2]))

In [18]:
A=np.array(adj)
hub1,auth1=calc_hits(A)
hub2,auth2=principal_eigen(np.matmul(A,A.T)),principal_eigen(np.matmul(A.T,A))
hub1,hub2,auth1,auth2

42


(array([0.04305011, 0.14444089, 0.02950849, 0.187491  , 0.2676258 ,
        0.14444089, 0.15393433, 0.02950849]),
 array([0.04305011, 0.14444089, 0.02950849, 0.187491  , 0.2676258 ,
        0.14444089, 0.15393432, 0.02950849]),
 array([0.08751959, 0.18704574, 0.3690361 , 0.12768284, 0.0593629 ,
        0.10998993, 0.        , 0.0593629 ]),
 array([ 0.08751959,  0.18704574,  0.3690361 ,  0.12768284,  0.0593629 ,
         0.10998993, -0.        ,  0.0593629 ]))

 RECOMMENDATION SYSTEM

In [19]:
import numpy as np
from enum import Enum

In [27]:
class Method(Enum):
  USER='User'
  ITEM='Item'

class RecommendationSystem:
  def __init__(self,ratings,method=Method.USER):
    self.ratings=(np.array(ratings) if method==Method.USER else np.array(ratings).T)
    self.num_rows,self.col_nums=self.ratings.shape
    self.method=method

  def cosine_similarity(self,vec1,vec2):
    mask=(vec1!=-1) & (vec2!=-1)
    vec1_masked=vec1[mask]
    vec2_masked=vec2[mask]
    norm1=np.linalg.norm(vec1_masked)
    norm2=np.linalg.norm(vec2_masked)

    if norm1==0 or norm2==0:
      return 0
    return np.dot(vec1_masked,vec2_masked)/(norm1*norm2)

  def predict_ratings(self,user_id,item_id,k):
    if self.method==Method.USER:
      row_id=user_id
      col_id=item_id
    else:
      row_id=item_id
      col_id=user_id
    ratings=self.ratings[row_id]
    similarities=[]

    for i in range(self.num_rows):
      if i!=row_id:
        other_ratings=self.ratings[i]
        similarities.append((i,self.cosine_similarity(ratings,other_ratings)))
    similarities.sort(key=lambda x:x[1],reverse=True)
    top_k_similarities=similarities[:k]

    weighted_sum=0
    total_similarity=0

    for id,similarity in top_k_similarities:
      if self.ratings[id][col_id]!=-1:
        weighted_sum+=similarity*self.ratings[id][col_id]
        total_similarity+=similarity
    if total_similarity==0:
      return 0
    return weighted_sum/total_similarity

In [29]:
ratings = [
    [5, 3, -1, -1, 2],
    [4, -1, -1, 2, 1],
    [1, 1, -1, 4, 5],
    [-1, -1, 4, 3, -1],
    [-1, -1, 4, 1, -1]
]

rs1=RecommendationSystem(ratings,Method.USER)
prediction=rs1.predict_ratings(user_id=3,item_id=0,k=3)
print(f"Predicted Rating ({Method.USER}-based): ",prediction)

rs2=RecommendationSystem(ratings,Method.USER)
prediction=rs2.predict_ratings(user_id=0,item_id=4,k=3)
print(f"Predicted Rating ({Method.ITEM}-based): ",prediction)

Predicted Rating (Method.USER-based):  2.5
Predicted Rating (Method.ITEM-based):  2.447599500269561
